### PR TITLE
Add in consul warning

### PR DESCRIPTION
**Pull request by bdronneau**

### CODE REVIEW

**Comment by bdronneau** [comment]
Il y a un bug que ça se met en vert si l'agent est unreacheable

**Comment by eilgin** [comment]
I've just seen that since `prod-puppetmaster` is unreachable :smile: 

``` shell
[{:label=>"ConsulCPMprod", :value=>"[] Unreachable Agent"}]
```

**Comment by bdronneau** [comment]
Ok fix

**Comment by eilgin** [comment]
:+1:

**Pull request merged**
